import { Platform } from "react-native";

export const Colors = {
  light: {
    text: "#1A1A2E",
    secondaryText: "#4A4A68",
    buttonText: "#FFFFFF",
    tabIconDefault: "#6B6B8C",
    tabIconSelected: "#6366F1",
    link: "#6366F1",
    accent: "#6366F1",
    accentSecondary: "#8B5CF6",
    highlight: "rgba(99, 102, 241, 0.15)",
    backgroundRoot: "#FAFAFA",
    backgroundDefault: "#FFFFFF",
    backgroundSecondary: "#F5F5F7",
    backgroundTertiary: "#EBEBF0",
    progressBar: "#6366F1",
    border: "#E5E5EA",
    borderSubtle: "#F0F0F5",
    placeholder: "#9CA3AF",
    success: "#10B981",
    warning: "#F59E0B",
    error: "#EF4444",
    glass: "rgba(255, 255, 255, 0.72)",
    glassStrong: "rgba(255, 255, 255, 0.85)",
    glassBorder: "rgba(255, 255, 255, 0.5)",
    shadow: "rgba(0, 0, 0, 0.08)",
  },
  dark: {
    text: "#F5F5F7",
    secondaryText: "#A1A1AA",
    buttonText: "#FFFFFF",
    tabIconDefault: "#71717A",
    tabIconSelected: "#818CF8",
    link: "#818CF8",
    accent: "#818CF8",
    accentSecondary: "#A78BFA",
    highlight: "rgba(129, 140, 248, 0.2)",
    backgroundRoot: "#0A0A0F",
    backgroundDefault: "#18181B",
    backgroundSecondary: "#27272A",
    backgroundTertiary: "#3F3F46",
    progressBar: "#818CF8",
    border: "#3F3F46",
    borderSubtle: "#27272A",
    placeholder: "#52525B",
    success: "#34D399",
    warning: "#FBBF24",
    error: "#F87171",
    glass: "rgba(24, 24, 27, 0.72)",
    glassStrong: "rgba(24, 24, 27, 0.85)",
    glassBorder: "rgba(255, 255, 255, 0.08)",
    shadow: "rgba(0, 0, 0, 0.4)",
  },
  sepia: {
    text: "#3D2E1F",
    secondaryText: "#6B5744",
    buttonText: "#FFFFFF",
    tabIconDefault: "#8B7355",
    tabIconSelected: "#A0785C",
    link: "#A0785C",
    accent: "#A0785C",
    accentSecondary: "#C4956A",
    highlight: "rgba(160, 120, 92, 0.2)",
    backgroundRoot: "#F8F4EC",
    backgroundDefault: "#FAF6EE",
    backgroundSecondary: "#F0EBE1",
    backgroundTertiary: "#E8E2D6",
    progressBar: "#A0785C",
    border: "#E0D9CC",
    borderSubtle: "#EDE7DD",
    placeholder: "#A89880",
    success: "#6B8E6B",
    warning: "#C4956A",
    error: "#C97A7A",
    glass: "rgba(250, 246, 238, 0.75)",
    glassStrong: "rgba(250, 246, 238, 0.88)",
    glassBorder: "rgba(139, 115, 85, 0.15)",
    shadow: "rgba(61, 46, 31, 0.08)",
  },
  dusk: {
    text: "#E8E4F0",
    secondaryText: "#A5A0B8",
    buttonText: "#FFFFFF",
    tabIconDefault: "#7A758C",
    tabIconSelected: "#B794F6",
    link: "#B794F6",
    accent: "#B794F6",
    accentSecondary: "#D4BBFF",
    highlight: "rgba(183, 148, 246, 0.2)",
    backgroundRoot: "#1A1625",
    backgroundDefault: "#241F32",
    backgroundSecondary: "#2E2840",
    backgroundTertiary: "#3A334D",
    progressBar: "#B794F6",
    border: "#3A334D",
    borderSubtle: "#2E2840",
    placeholder: "#6B6580",
    success: "#7EDAB0",
    warning: "#F5C87A",
    error: "#F0888E",
    glass: "rgba(36, 31, 50, 0.75)",
    glassStrong: "rgba(36, 31, 50, 0.88)",
    glassBorder: "rgba(183, 148, 246, 0.15)",
    shadow: "rgba(0, 0, 0, 0.35)",
  },
  midnight: {
    text: "#E5E5E5",
    secondaryText: "#8B8B8B",
    buttonText: "#FFFFFF",
    tabIconDefault: "#666666",
    tabIconSelected: "#3B82F6",
    link: "#3B82F6",
    accent: "#3B82F6",
    accentSecondary: "#60A5FA",
    highlight: "rgba(59, 130, 246, 0.2)",
    backgroundRoot: "#000000",
    backgroundDefault: "#0A0A0A",
    backgroundSecondary: "#141414",
    backgroundTertiary: "#1F1F1F",
    progressBar: "#3B82F6",
    border: "#262626",
    borderSubtle: "#1A1A1A",
    placeholder: "#4B4B4B",
    success: "#22C55E",
    warning: "#EAB308",
    error: "#EF4444",
    glass: "rgba(10, 10, 10, 0.8)",
    glassStrong: "rgba(10, 10, 10, 0.92)",
    glassBorder: "rgba(255, 255, 255, 0.05)",
    shadow: "rgba(0, 0, 0, 0.6)",
  },
  forest: {
    text: "#E8EDE8",
    secondaryText: "#9CAA9C",
    buttonText: "#FFFFFF",
    tabIconDefault: "#6B7D6B",
    tabIconSelected: "#4ADE80",
    link: "#4ADE80",
    accent: "#4ADE80",
    accentSecondary: "#86EFAC",
    highlight: "rgba(74, 222, 128, 0.2)",
    backgroundRoot: "#0F1A14",
    backgroundDefault: "#162419",
    backgroundSecondary: "#1E2F23",
    backgroundTertiary: "#283A2D",
    progressBar: "#4ADE80",
    border: "#2D4532",
    borderSubtle: "#1E2F23",
    placeholder: "#4D6050",
    success: "#4ADE80",
    warning: "#BEF264",
    error: "#FB7185",
    glass: "rgba(22, 36, 25, 0.75)",
    glassStrong: "rgba(22, 36, 25, 0.88)",
    glassBorder: "rgba(74, 222, 128, 0.12)",
    shadow: "rgba(0, 0, 0, 0.35)",
  },
};

export type ThemeMode = "light" | "dark" | "sepia" | "dusk" | "midnight" | "forest";

export const ThemeNames: Record<ThemeMode, string> = {
  light: "Day",
  dark: "Night",
  sepia: "Paper",
  dusk: "Dusk",
  midnight: "AMOLED",
  forest: "Forest",
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  "2xl": 24,
  "3xl": 32,
  "4xl": 40,
  "5xl": 48,
  "6xl": 64,
  inputHeight: 48,
  buttonHeight: 52,
};

export const BorderRadius = {
  xs: 6,
  sm: 10,
  md: 14,
  lg: 20,
  xl: 28,
  "2xl": 36,
  "3xl": 44,
  full: 9999,
};

export const Typography = {
  h1: {
    fontSize: 34,
    fontWeight: "700" as const,
    letterSpacing: -0.5,
  },
  h2: {
    fontSize: 28,
    fontWeight: "700" as const,
    letterSpacing: -0.3,
  },
  h3: {
    fontSize: 22,
    fontWeight: "600" as const,
    letterSpacing: -0.2,
  },
  h4: {
    fontSize: 18,
    fontWeight: "600" as const,
    letterSpacing: -0.1,
  },
  body: {
    fontSize: 16,
    fontWeight: "400" as const,
    letterSpacing: 0,
  },
  bodyLarge: {
    fontSize: 17,
    fontWeight: "400" as const,
    letterSpacing: 0.1,
  },
  small: {
    fontSize: 14,
    fontWeight: "400" as const,
    letterSpacing: 0.1,
  },
  caption: {
    fontSize: 12,
    fontWeight: "500" as const,
    letterSpacing: 0.2,
  },
  link: {
    fontSize: 16,
    fontWeight: "500" as const,
    letterSpacing: 0,
  },
};

export const Motion = {
  duration: {
    instant: 100,
    fast: 150,
    normal: 250,
    slow: 350,
    gentle: 500,
  },
  easing: {
    easeOut: { x1: 0, y1: 0, x2: 0.2, y2: 1 },
    easeIn: { x1: 0.4, y1: 0, x2: 1, y2: 1 },
    easeInOut: { x1: 0.4, y1: 0, x2: 0.2, y2: 1 },
    spring: { damping: 15, stiffness: 150 },
    springGentle: { damping: 20, stiffness: 120 },
    springSnappy: { damping: 12, stiffness: 200 },
    bounce: { damping: 8, stiffness: 180 },
  },
};

export const ReadingDefaults = {
  fontSize: 18,
  lineSpacing: 1.6,
  marginHorizontal: 24,
  letterSpacing: 0.3,
  paragraphSpacing: 1.2,
  minFontSize: 14,
  maxFontSize: 32,
  minLineSpacing: 1.2,
  maxLineSpacing: 2.2,
  minLetterSpacing: -0.5,
  maxLetterSpacing: 2.0,
  optimalLineLength: 66,
  minLineLength: 50,
  maxLineLength: 75,
  paddingTop: 40,
  paddingBottom: 60,
  minPadding: 20,
  maxPadding: 120,
};

export const Fonts = Platform.select({
  ios: {
    sans: "-apple-system",
    serif: "Georgia",
    rounded: "ui-rounded",
    mono: "SF Mono",
  },
  default: {
    sans: "System",
    serif: "serif",
    rounded: "System",
    mono: "monospace",
  },
  web: {
    sans: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', Times, serif",
    rounded: "-apple-system, BlinkMacSystemFont, 'SF Pro Rounded', Roboto, 'Helvetica Neue', sans-serif",
    mono: "SF Mono, Monaco, 'Courier New', monospace",
  },
});

export const AvailableFonts = [
  { name: "System", value: "system", description: "Clean, modern system font" },
  { name: "Serif", value: "serif", description: "Classic book-style font" },
  { name: "Georgia", value: "georgia", description: "Elegant, readable serif" },
  { name: "Times", value: "times", description: "Traditional newspaper font" },
  { name: "Palatino", value: "palatino", description: "Refined, literary feel" },
];

export const ReadingModes = {
  standard: {
    name: "Standard",
    description: "Balanced reading experience",
    fontSize: 18,
    lineSpacing: 1.6,
    letterSpacing: 0.3,
  },
  comfortable: {
    name: "Comfortable",
    description: "Relaxed, easy on the eyes",
    fontSize: 20,
    lineSpacing: 1.8,
    letterSpacing: 0.4,
  },
  compact: {
    name: "Compact",
    description: "More content per page",
    fontSize: 16,
    lineSpacing: 1.4,
    letterSpacing: 0.2,
  },
  focus: {
    name: "Focus",
    description: "Optimized for deep reading",
    fontSize: 19,
    lineSpacing: 1.7,
    letterSpacing: 0.5,
  },
};

export type ReadingMode = keyof typeof ReadingModes;

export const ScrollModes = {
  seamless: {
    name: "Seamless Scroll",
    description: "Continuous finger scrolling",
  },
  autoScroll: {
    name: "Auto Scroll",
    description: "Automatic scrolling at set speed",
  },
  linearFocus: {
    name: "Linear Focus",
    description: "Line-by-line guided reading for ADHD",
  },
};

export type ScrollMode = keyof typeof ScrollModes;

export const AutoScrollDefaults = {
  minSpeed: 10,
  maxSpeed: 200,
  defaultSpeed: 50,
};

export const LinearFocusDefaults = {
  minVisibleLines: 1,
  maxVisibleLines: 5,
  defaultVisibleLines: 1,
  highlightCurrentLine: true,
  dimOpacity: 0.15,
};

export const Shadows = {
  sm: {
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  md: {
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  lg: {
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
  },
  xl: {
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 10,
  },
};
